# apiVersion: v1
# kind: Service
# metadata:
#   name: nginx-ingress-mutating-admission-controller
#   labels:
#     app: nginx-ingress-mutating-admission-controller
# spec:
#   ports:
#   - port: 80
#     targetPort: 8080
#     protocol: TCP
#     name: http
#   selector:
#     app: nginx-ingress-mutating-admission-controller
